# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'NewsFeedFB-VK' do
pod 'MagicalRecord/Shorthand'
pod 'MBProgressHUD', :git => 'https://github.com/jdg/MBProgressHUD.git', :tag => '1.0.0'
pod 'SDWebImage'
pod 'VK-ios-sdk'
pod 'AFNetworking'
pod 'FRHyperLabel'

end
